:sparkles: Lot of stuff going on

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -9,13 +9,13 @@ linter_exit_code=1
 tsc_exit_code=1
 staged_ts_files=$(git diff --cached --diff-filter=d --name-only | grep -E "(.ts$|.tsx$)")
 
-if [ -n $staged_ts_files ]
-  then
-    echo "${BROWN} 🥺 No .ts | .tsx files, skipping checks${NC}"
-    exit 0
+if [ -n $staged_ts_files ]; then
+  echo "${BROWN} 🥺 No .ts | .tsx files, skipping checks${NC}"
+  echo "${BROWN} 🥺 ABORT ${NC}"
+  exit 0
 fi
 
-echo "👀 Checking ESLint..."
+echo "${BROWN} 👀 Checking ESLint...${NC}"
 
 ./node_modules/.bin/eslint $staged_ts_files --quiet --fix
 linter_exit_code=$?
@@ -27,7 +27,7 @@ if [ $linter_exit_code -ne 0 ]
     echo "${GREEN} ✔ ESLint${NC}"
 fi
 
-echo "👀 Checking Typescript..."
+echo "${BROWN} 👀 Checking Typescript...${NC}"
 
 ./node_modules/.bin/tsc || exit 0
 tsc_exit_code=$?
@@ -39,11 +39,10 @@ if [ $tsc_exit_code -ne 0 ]
     echo "${GREEN} ✔ Typescript${NC}"
 fi
 
-if [ $linter_exit_code == 0 && $tsc_exit_code == 0 ]
-  then
-    echo "${GREEN} ✔ Files added to staging!${NC}"
-    git add -f $staged_ts_files
-    exit 0
-  else
-    exit 1
+if [ $linter_exit_code -eq 0 ] && [ $tsc_exit_code -eq 0 ]; then
+  # git add .
+  echo "${GREEN} ✔ Files added to staging!${NC}"
+  exit 0
+else
+  exit 1
 fi
