:contruction_worker: Improved CI with audit local

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,17 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-npx lint-staged
+audit_result="npm audit --audit-level=moderate"
+
+exit_code=$?
+
+if [ "$exit_code" -ne "0" ] ; then
+  echo "npm audit failed"
+  echo "npm audit output:"
+  echo "$audit_result"
+  exit 1
+else
+  echo "✅ npm audit passed"
+fi
+
+npx lint-staged --concurrent true
